version: '3'

services:
  dbt:
    # image: ghcr.io/dbt-labs/dbt-core:${DBT_VERSION:-1.4.4}
    build: 
      context: ./
    volumes:
      - "./dbt_project/:/usr/app"
      - "./profiles.yml:/root/.dbt/profiles.yml"
    ports:
      - 9000:9090
    command: "docs serve --port 9090"
    environment:
      - DBT_USER=de_user
      - DBT_PASSWORD=de_pass
    tty: true
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}
networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}