version: '3'

services:
  dbt-run:
    build: 
      context: ./
    image: de-toolkit/dbt
    volumes:
      - "./dbt_project/:/usr/app"
      - "./profiles.yml:/root/.dbt/profiles.yml:r"
    command: "run"
    environment:
      - DBT_USER=de_user
      - DBT_PASSWORD=de_pass
    tty: true
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}
  
  dbt-docs-gen:
    image: de-toolkit/dbt
    volumes:
      - "./dbt_project/:/usr/app"
      - "./profiles.yml:/root/.dbt/profiles.yml:r"
    command: "docs generate"
    environment:
      - DBT_USER=de_user
      - DBT_PASSWORD=de_pass
    tty: true
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}

  dbt-docs:
    image: de-toolkit/dbt
    volumes:
      - "./dbt_project/:/usr/app"
      - "./profiles.yml:/root/.dbt/profiles.yml:r"
    ports:
      - 7000:7000
    command: "docs serve --port 7000"
    environment:
      - DBT_USER=de_user
      - DBT_PASSWORD=de_pass
    tty: true
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}

networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}