version: '3'

networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}

volumes:
  metabase-db:

x-toolkit-common: &toolkit-common
  networks:
    - ${DOCKER_NETWORK:-de-toolkit-net}  

services:
  metabase-db:
    image: 'bitnami/postgresql:${METABASE_PG_VERSION:-latest}'
    # ports:
    #   - '25432:5432'
    <<: *toolkit-common
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${DE_DB_NAME:-de} -U $${DE_USERNAME:-de_user} || exit 1
      timeout: 2s
    volumes:
      - metabase-db:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=metabase
      - POSTGRESQL_USERNAME=${DE_USERNAME:-de_user}
      - POSTGRESQL_PASSWORD=${DE_PASSWORD:-de_pass}
# metabase
  metabase:
    image: metabase/metabase:${METABASE_VERSION:-latest}
    container_name: metabase
    depends_on:
      - metabase-db
    hostname: metabase
    ports:
      - "3000:3000"
    <<: *toolkit-common
    volumes:
      - "./plugins:/plugins"
      - "./data:/metabase-data"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${DE_USERNAME:-de_user}
      - MB_DB_PASS=${DE_PASSWORD:-de_pass}
      - MB_DB_HOST=metabase-db
