version: '3'

services:
# airflow (depends on postgresql)
  airflow-postgresql:
    image: bitnami/postgresql:${AIRFLOW_DATABASE_VERSION:-airflow}
    ports:
      - "15432:15432"
    volumes:
      - './airflow/postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=${AIRFLOW_DATABASE:-airflow}
      - POSTGRESQL_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - POSTGRESQL_USERNAME=${DE_USERNAME:-de_user}
      - POSTGRESQL_PASSWORD=${DE_PASSWORD:-de_pass}
      #- ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./airflow/redis:/bitnami/redis"
  airflow-worker:
    image: bitnami/airflow-worker:${AIRFLOW_VERSION:-latest}
    depends_on:
      - airflow-postgresql
      - redis
    volumes:
      - "./airflow/dags:/opt/bitnami/airflow/dags"
      - "./airflow/dags/requirements.txt:/bitnami/python/requirements.txt"
      - "./airflow/plugins:/opt/bitnami/airflow/plugins"
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - AIRFLOW_DATABASE_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE:-airflow}
      - AIRFLOW_DATABASE_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_DATABASE_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow-scheduler:
    image: bitnami/airflow-scheduler:${AIRFLOW_VERSION:-latest}
    depends_on:
      - airflow-postgresql
      - airflow
      - redis
    volumes:
      - "./airflow/dags:/opt/bitnami/airflow/dags"
      - "./airflow/dags/requirements.txt:/bitnami/python/requirements.txt"
      - "./airflow/plugins:/opt/bitnami/airflow/plugins"
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - AIRFLOW_DATABASE_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE:-airflow}
      - AIRFLOW_DATABASE_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_DATABASE_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow:
    image: bitnami/airflow:${AIRFLOW_VERSION:-latest}
    depends_on:
      - airflow-postgresql
      - redis    
    volumes:
      - "./airflow/dags:/opt/bitnami/airflow/dags"
      - "./airflow/dags/requirements.txt:/bitnami/python/requirements.txt"
      - "./airflow/plugins:/opt/bitnami/airflow/plugins"
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - AIRFLOW_DATABASE_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE:-airflow}
      - AIRFLOW_DATABASE_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_DATABASE_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8080:8080'
# postgresql
  postgresql:
    image: 'bitnami/postgresql:${PG_VERSION:-latest}'
    container_name: postgresql
    hostname: postgresql
    ports:
      - '5432:5432'
    volumes:
      - "./postgresql/data:/bitnami/postgresql"
#      - "./airflow/1_create_de_user_d.sql:/docker-entrypoint-initdb.d/1_create_de_user_db.sql"
#      - "./airflow/create_airflow_db.sql:/docker-entrypoint-initdb.d/create_airflow_db.sql"
      - "./metabase/create_metabase_db.sql:/docker-entrypoint-initdb.d/create_metabase_db.sql"
    environment:
      - POSTGRESQL_DATABASE=${DE_DB_NAME:-de}
      - POSTGRESQL_USERNAME=${DE_USERNAME:-de_user}
      - POSTGRESQL_PASSWORD=${DE_PASSWORD:-de_pass}
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${DE_DB_NAME:-de} -U $${DE_USERNAME:-de_user} || exit 1
# metabase
  metabase:
    image: metabase/metabase:${METABASE_VERSION:-latest}
    container_name: metabase
    depends_on:
      - postgresql
    hostname: metabase
    ports:
      - "3000:3000"
    volumes:
      - "./metabase/plugins:/plugins"
      - "./metabase/data:/metabase-data"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${DE_USERNAME:-de_user}
      - MB_DB_PASS=${DE_PASSWORD:-de_pass}
      - MB_DB_HOST=postgresql