version: '3'

networks:
  de-toolkit:
    driver: bridge

services:
  cronicle:
    image: bluet/cronicle-docker:0.9.7
    container_name: cronicle
    hostname: cronicle
    ports:
      - "3012:3012" 
    networks:
      - de-toolkit
    restart: unless-stopped
    volumes:
      - "./cronicle/data/:/opt/cronicle/data:rw"
      - "./cronicle/logs:/opt/cronicle/logs:rw"
      - "./cronicle/plugins:/opt/cronicle/plugins:rw"
      - "./cronicle/app:/app:rw"
    environment:
      - CRONICLE_WebServer__http_port=3012
      - CRONICLE_server_comm_use_hostnames=1
  postgresql:
    image: 'bitnami/postgresql:14.4.0'
    container_name: postgreql
    hostname: postgreql
    ports:
      - '5432:5432'
    networks:
      - de-toolkit
    volumes:
      - './postgresql/data:/bitnami/postgresql'
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=de_user
      - POSTGRESQL_PASSWORD=de_password
      - POSTGRESQL_DATABASE=de
