version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:${CH_VERSION:-latest}
    hostname: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - "./clickhouse/data:/var/lib/clickhouse/"
      - "./clickhouse/logs:/var/log/clickhouse-server/"
#      - "./clickhouse/config.xml:/etc/clickhouse-server/config.xml"
#      - "./clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
    environment:
      - CLICKHOUSE_DB=${DE_DB_NAME:-de}
      - CLICKHOUSE_USER=${DE_USERNAME:-de_user}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 
      - CLICKHOUSE_PASSWORD=${DE_PASSWORD:-de_pass}
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}
  postgresql:
    image: 'bitnami/postgresql:${PG_VERSION:-latest}'
    container_name: postgresql
    hostname: postgresql
    ports:
      - '5432:5432'
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}
    volumes:
      - "./postgresql/data:/bitnami/postgresql"
#      - "./airflow/1_create_de_user_d.sql:/docker-entrypoint-initdb.d/1_create_de_user_db.sql"
#      - "./airflow/create_airflow_db.sql:/docker-entrypoint-initdb.d/create_airflow_db.sql"
      - "./metabase/create_metabase_db.sql:/docker-entrypoint-initdb.d/create_metabase_db.sql"
    environment:
      - POSTGRESQL_DATABASE=${DE_DB_NAME:-de}
      - POSTGRESQL_USERNAME=${DE_USERNAME:-de_user}
      - POSTGRESQL_PASSWORD=${DE_PASSWORD:-de_pass}
# metabase
  metabase:
    image: metabase/metabase:${METABASE_VERSION:-latest}
    container_name: metabase
    depends_on:
      - postgresql
    hostname: metabase
    ports:
      - "3000:3000"
    networks:
      - ${DOCKER_NETWORK:-de-toolkit-net}
    volumes:
      - "./metabase/plugins:/plugins"
      - "./metabase/data:/metabase-data"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${DE_USERNAME:-de_user}
      - MB_DB_PASS=${DE_PASSWORD:-de_pass}
      - MB_DB_HOST=postgresql
networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}