version: '3'

networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}

x-toolkit-common: &toolkit-common
  networks:
    - ${DOCKER_NETWORK:-de-toolkit-net}  

services:
# cronicle
  cronicle:
    <<: *toolkit-common
    image: bluet/cronicle-docker:${CRONICLE_VERSION:-latest}
    container_name: cronicle
    hostname: cronicle
    ports:
      - "8080:3012" 
    restart: unless-stopped
    volumes:
      - "./cronicle/data/:/opt/cronicle/data:rw"
      - "./cronicle/logs:/opt/cronicle/logs:rw"
      - "./cronicle/plugins:/opt/cronicle/plugins:rw"
      - "./cronicle/app:/app:rw"
    environment:
      - CRONICLE_WebServer__http_port=3012
      - CRONICLE_server_comm_use_hostnames=1
# postgresql
  postgresql:
    <<: *toolkit-common
    image: 'bitnami/postgresql:${PG_VERSION:-latest}'
    container_name: postgresql
    hostname: postgresql
    ports:
      - '5432:5432'
    volumes:
      - "./postgresql/data:/bitnami/postgresql"
      - "./metabase/create_metabase_db.sql:/docker-entrypoint-initdb.d/create_metabase_db.sql"
    environment:
      - POSTGRESQL_DATABASE=${DE_DB_NAME:-de}
      - POSTGRESQL_USERNAME=${DE_USERNAME:-de_user}
      - POSTGRESQL_PASSWORD=${DE_PASSWORD:-de_pass}
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${DE_DB_NAME:-de} -U $${DE_USERNAME:-de_user} || exit 1
# metabase
  metabase:
    <<: *toolkit-common
    image: metabase/metabase:${METABASE_VERSION:-latest}
    container_name: metabase
    depends_on:
      - postgresql
    hostname: metabase
    ports:
      - "3000:3000"
    volumes:
      - "./metabase/plugins:/plugins"
      - "./metabase/data:/metabase-data"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${DE_USERNAME:-de_user}
      - MB_DB_PASS=${DE_PASSWORD:-de_pass}
      - MB_DB_HOST=postgresql