version: '3.9'
services:
  dagsterdev:
    build: 
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    image: dagster-example-pipeline-dev
    ports: 
      - "8002:3000"
    # environment:
    #   SLACK_HOOK: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
    volumes:
      - ./:/usr/src/app
    networks:
      - de-toolkit-net

networks:
  de-toolkit-net:
    name: de-toolkit-net
    # external: true
