version: "3.9"

x-toolkit-common: &toolkit-common
  networks:
    - ${DOCKER_NETWORK:-de-toolkit-net}  

services:

  ### Prefect prefect_db
  prefect_db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    # expose:
    #   - 5432
    volumes: 
      - prefect_db_data:/var/lib/postgresql/data
    <<: *toolkit-common
    profiles: ["server"]
  
  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:2.10.7-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@prefect_db:5432/prefect
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - 4200:4200
    depends_on:
      - prefect_db
    <<: *toolkit-common
    profiles: ["server"]

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.10.7-python3.11
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "default"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
    volumes:
      - "./flows:/root/flows:ro"
    <<: *toolkit-common
    profiles: ["agent"]

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.10.7-python3.11
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows:rw"
    tty: true
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
    <<: *toolkit-common
    profiles: ["cli"]
      
volumes:
  prefect:
  prefect_db_data:
  prefect_minio:

networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}

