version: '3.8'

volumes:
  airflow_postgresql_data:
  airflow_redis_data:
  airflow_logs:

services:
# airflow (depends on postgresql)
  airflow-postgresql:
    image: bitnami/postgresql:${AIRFLOW_DATABASE_VERSION:-latest}
    ports:
      - "15432:15432"
    volumes:
      - "airflow_postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_DATABASE=${AIRFLOW_DATABASE:-airflow}
      - POSTGRESQL_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - POSTGRESQL_USERNAME=${DE_USERNAME:-de_user}
      - POSTGRESQL_PASSWORD=${DE_PASSWORD:-de_pass}
      #- ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "airflow_redis_data:/bitnami/redis"
  airflow-worker:
    image: bitnami/airflow-worker:${AIRFLOW_VERSION:-latest}
    depends_on:
      - airflow-postgresql
      - redis
    volumes:
      - "./dags:/opt/bitnami/airflow/dags"
      - "airflow_logs:/opt/bitnami/airflow/logs"
      - "./dags/requirements.txt:/bitnami/python/requirements.txt"
      - "./plugins:/opt/bitnami/airflow/plugins"
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - AIRFLOW_DATABASE_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE:-airflow}
      - AIRFLOW_DATABASE_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_DATABASE_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow-scheduler:
    image: bitnami/airflow-scheduler:${AIRFLOW_VERSION:-latest}
    depends_on:
      - airflow-postgresql
      - airflow
      - redis
    volumes:
      - "./dags:/opt/bitnami/airflow/dags"
      - "airflow_logs:/opt/bitnami/airflow/logs"
      - "./dags/requirements.txt:/bitnami/python/requirements.txt"
      - "./plugins:/opt/bitnami/airflow/plugins"
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - AIRFLOW_DATABASE_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE:-airflow}
      - AIRFLOW_DATABASE_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_DATABASE_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow:
    image: bitnami/airflow:${AIRFLOW_VERSION:-latest}
    depends_on:
      - airflow-postgresql
      - redis    
    volumes:
      - "./dags:/opt/bitnami/airflow/dags"
      - "airflow_logs:/opt/bitnami/airflow/logs"
      - "./dags/requirements.txt:/bitnami/python/requirements.txt"
      - "./plugins:/opt/bitnami/airflow/plugins"
      - "/var/run/docker.sock:/var/run/docker.sock:rw" #to run docker containers using DockerOperator
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_HOST=airflow-postgresql
      - AIRFLOW_DATABASE_PORT_NUMBER=${AIRFLOW_DATABASE_PORT:-15432}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE:-airflow}
      - AIRFLOW_DATABASE_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_DATABASE_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_PASSWORD=${DE_PASSWORD:-de_pass}
      - AIRFLOW_USERNAME=${DE_USERNAME:-de_user}
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8000:8080'
