version: '3.9'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DB: ${DE_DB_NAME}
      POSTGRES_USER: ${DE_USERNAME}
      POSTGRES_PASSWORD: ${DE_PASSWORD}
      POSTGRES_HOST: postgresql
      PG_HOST_PORT: 5432
      # ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    networks:
      - de-toolkit-net

networks:
  de-toolkit-net:
    name: de-toolkit-net
    # external: true
