version: "3.9"

x-toolkit-common: &toolkit-common
  networks:
    - ${DOCKER_NETWORK:-de-toolkit-net}  

services: 
  ### MinIO for flow storage
  minio:
    image: bitnami/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9001", "--console-address", "0.0.0.0:9002", "/data"]
    volumes:
      - "minio_data:/data"
    ports:
      - 9001:9001
      - 9002:9002
    environment:
      - MINIO_ROOT_USER=${DE_USERNAME:-de_user}
      - MINIO_ROOT_PASSWORD=${DE_PASSWORD:-de_password} # should be longer when 8 symbols
    <<: *toolkit-common
      
volumes:
  minio_data:

networks:
  de-toolkit-net:
    name: ${DOCKER_NETWORK:-de-toolkit-net}

